### ISSUE TITLE
Infinite Loading Loop for poorly developed websites

### ISSUE THREAD

**Issue by navarr** [edlea/DesktopAMP#12]
Websites where the AMP page points to the exact same page my infinitely loop trying to fetch the AMP page.

Example: https://www.bizjournals.com/bizjournals/how-to/marketing/2016/04/the-massive-mistake-you-are-making-on-linkedin.amp.html

**Comment by vrwarp** [comment]
Happens on certain (many?) NYTimes pages too: http://mobile.nytimes.com/2016/05/06/nyregion/students-at-fake-university-say-they-were-collateral-damage-in-sting-operation.amp.html

I think what happens is the non-amp page has the amp link. But the amp link redirects back to the non-amp page.

**Comment by paulirish** [comment]
nytimes gives me this behavior 85% of the time. incognito is typically my "fix", though clearly it'd be better to address in the project.

Here you can see the redirect loop in action: 
![image](https://cloud.githubusercontent.com/assets/39191/17142311/ae9a7afc-531d-11e6-9e86-1b1640f18530.png)

These pages hit this behavior almost certainly because they're redirecting non-mobile browsers to desktop URLs.  (Which I can't blame them for)

---

I looked into some options and curious what others think.  @navarr @vrwarp  @clipperhouse  

### option 1: spoof the useragent with the webrequest api

the webrequest API can help us to spoof the useragent to be a mobile browser. This will definitely fix the issue on these sites, however the webrequest API adds extra latency to all the network requests it touches, so the perf impact is moderate.

##### 1a) Apply the webrequest override on all URLs

This is the blanket approach of sending all network requests though this API and making the adjustment when neccessary.  It adds extra overhead, but i'll be low maintenance.

##### 1b) Apply the override to a domain whitelist

We could also just add mobile.nytimes.com, bizjournals and whoever else to a whitelist and only mess with those URLs. Perf wise, this would be much preferable, but we'd have to maintain this whitelist.

### option 2: detect the redirect loop and quit attempting to redirect

This option is a failure state. We would not end up with the AMP page. However the desktop page _would_ load successfully, which I'd be happy with. :)

We'd use the history API to detect a redirect loop and therefore avoid quit our own `window.location = ...` navigation.

---

The permissions required for 1 are more invasive, but since we already ask for "read and change all your data on the websites you visit", it wouldn't make a difference to the user.

Personally I favor option 2 for now, though if someone was up to contributing/maintaining option 1b, I'd give it a 👍 

Thoughts?

**Comment by paulirish** [comment]
(I half-prototyped this stuff, so here's my code https://gist.github.com/paulirish/32926562956b983dc283de09afa0eb66 )

**Comment by edlea** [comment]
I've just created #15 that implements option 2. Be good to get your thoughts, @paulirish, before I merge.

It also includes some changes to the project structure to make it easier to maintain the Safari and Chrome extensions (this fix is Chrome only at the moment)

**Comment by clipperhouse** [comment]
I like Option 1, a mobile UA is effectively the same high-level use case: show me the version optimized for mobile.

(If we think that’s too invasive, could whitelist certain sites but that has downsides too, in that it’s inconsistent behavior that the user might not understand.)

Option 2 is good too, not mutually exclusive, stop the degenerate case.

Third idea is to treat this like Safari treats Reader Mode: it’s an option that’s detected/enabled, but you click the button to see the AMP view.

**Comment by edlea** [comment]
This is fixed in 2.3.1 that's now live on the Chrome Web Store

**Comment by prenagha** [comment]
any hints on getting this fix into the safari extension as well?

**Comment by edlea** [comment]
@prenagha https://github.com/edlea/DesktopAMP/releases/tag/v2.3.1 is available now. I'll push a version to the Safari Extension directory too

**Comment by prenagha** [comment]
From the look of the code it seems the fix is coded to only apply to Chrome?
Anyway, just tried 2.3.1 in safari, downloaded from the release page and NYTimes still loops. For example

http://www.nytimes.com/2016/09/04/movies/alicia-vikander-michael-fassbender-interview-the-light-between-oceans.html?contentCollection=weekendreads

**Comment by edlea** [comment]
You're right, sorry @prenagha - I confused myself. The Safari fix should come later this week...
