### ISSUE TITLE
Faster initialization

### ISSUE THREAD

**Issue by paulirish** [edlea/DesktopAMP#4]
so we need to read the `<head>` and thus document_start won't work as a trigger.

but it feels like document_end is a bit too late. 

One approach that might work

in document_start, set up a mutationobserver, observe the documentElement, and when it adds a node, see if its the head, then querySelector in that for our amp guy. 

ideally that'd get things rolling faster than waiting for all of <body> to finish.

a bit more complicated but probably worth it, wdyt?

**Comment by edlea** [comment]
This is a great suggestion. I've just push an update (to Github and the CWS) that does this.

I wasn't familiar with mutationObserver. I was hoping to be able to call disconnect() on the observer but couldn't find a good place to do it. It seems that the <head> doesn't get updated in a single set of mutations before the <body>. Hopefully there won't be a noticeable performance impact of keeping the observer alive.

**Comment by paulirish** [comment]
nice!

i think we can disconnect it.

https://jsbin.com/hureme/1/edit?html,output has the flow. basically disconnect when we hit the `<body>` element.

also you can probably flip `attributes` to `false`.

**Comment by edlea** [comment]
I was sure I'd tried that, but you're absolutely right. I'll test on a few more sites and push.

The `attributes` flag makes sense too - I added that thinking it was needed to detect the ⚡️attribute on AMP pages (to force a max-width) but that will always be part of the original `<html>` mutation I think.

Thanks for the guidance. Much appreciated.

**Comment by edlea** [comment]
I think I spoke too soon. On The Verge (e.g. http://www.theverge.com/2015/10/21/9556153/internet-of-things-privacy-paranoia-data-volkswagen-scandal) it seems that the `<head>` is still being mutated when the `<body>` starts to be mutated.

On that page, there's a lot of `<script>` tags before our `<link>`. Possibly an optimisation to start parsing the `<body>` rather than blocking on the `<head>` while the JavaScript interpreter does its thing?

I've pushed SHA: 8a7dd0dc3421f9e73118ceca7ae0604f7b607261 that has the check and disconnect code in. It works on some sites, just not all.

**Comment by paulirish** [comment]
ah, can confirm: 
![image](https://cloud.githubusercontent.com/assets/39191/10654202/1e974246-781c-11e5-8181-84305d33d3cf.png)

**Comment by paulirish** [comment]
meta before the end is ours. 

and `<script src="https://cdn0.vox-cdn.com/javascripts/verge2_head.v6b1e078fb1d0829b.js"></script>` is what makes the `<body>`
